### ISSUE TITLE
Where to find Interop.PortableDeviceApiLib ?

### ISSUE THREAD

**Issue by XtroTheArctic** [Duke-fleed/WPDApi#8]
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Interop.PortableDeviceApiLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
  Source=PortableDevices
  StackTrace:
   at PortableDevices.PortableDeviceCollection..ctor()
   at WindowsFormsApp1.Form1.button1_Click(Object sender, EventArgs e) in E:\Windows\Onur\Desktop\iPhone'dan Foto taşıma tool'u\WindowsFormsApp1\Form1.cs:line 27
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at WindowsFormsApp1.Program.Main() in E:\Windows\Onur\Desktop\iPhone'dan Foto taşıma tool'u\WindowsFormsApp1\Program.cs:line 19

**Comment by bulletis** [comment]
I figure out this. In your project.
Reference -> Add Reference -> Select COM tab -> search with "Portable" -> check "PortableDevice Api 1.0 Type Library" -> click OK -> right click on "PortableDeviceApiLib" in your project's references -> select Property -> change "Embed Interop Types" to False -> make sure "Copy Local" is "True" -> rebuild your project.

**Comment by XtroTheArctic** [comment]
After so many times, this helped. I can continue working on my project now. Thank you very much.

**Comment by XtroTheArctic** [comment]
Yesterday I closed this ticket because your suggestion helped and PortableDeviceCollection constructor started working but today I continued working on my project and saw that, when there is one device (an iPHona) connected to my computer, PortableDeviceCollection contains 1 item in it. Then when I can call PortableDevice.Connect method, I still get a similar interop related error.

Why do you think this would fail while the PortableDeviceCollection constructor call works fine?

System.IO.FileNotFoundException: Could not load file or assembly 'Interop.PortableDeviceTypesLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Interop.PortableDeviceTypesLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at PortableDevices.PortableDevice.Connect()

**Comment by XtroTheArctic** [comment]
Ok. I figured this out.

I needed to do the same thing for PortableDeviceTypesLib similar to PortableDeviceApiLib.

I can connect to my iPhone now.

**Comment by bulletis** [comment]
I just found that this project's functions are limited.  So I did a google and found another candidate for MTP operation. And much more powwerful. Thinking about this project has not been updated for many years. I suggest you may also consider this one.
https://github.com/Bassman2/MediaDevices
Good luck!

**Comment by XtroTheArctic** [comment]
I'll check it. Thank you very much.
